# Dữ liệu Marketing Campaign (Customer Personality Analysis)
**Nguồn trong đề:** Lab 1 — mục 1.1.2 nhiệm vụ 2 và mục 1.3 (ydata_profiling, dtale, SweetViz, AutoViz)

Notebook độc lập cho một tập dữ liệu; code lấy từ các ô tương ứng của notebook Lab1 (giữ nguyên, ô nào chỉnh có ghi `# [Chỉnh]`).

In [1]:
# Thư viện dùng chung (đề import rải rác ở nhiều ô; gom lại để notebook chạy độc lập)
import os
if os.path.basename(os.getcwd()) == 'notebooks':   # chạy notebook từ thư mục notebooks/ thì lùi ra thư mục gốc chứa data/
    os.chdir('..')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

#### Nhiệm vụ 2: Khám phá và xử lý dữ liệu Marketing Campaign

In [2]:
import pandas as pd
# [Chỉnh] file Marketing Campaign (Kaggle) phân cách bằng dấu Tab nên cần sep='\t'
marketing_data = pd.read_csv("data/marketing_campaign.csv", sep='\t', encoding='utf-8-sig')
# [Chỉnh] tên cột đúng là 'Dt_Customer' (đề in nhầm 'Dt_ Customer')
marketing_data = marketing_data[['ID','Year_Birth', 'Education',
 'Marital_Status','Income','Kidhome', 'Teenhome',
 'Dt_Customer', 'Recency','NumStorePurchases',
 'NumWebVisitsMonth']]

**2. Loại bỏ dữ liệu trùng lặp**

In [3]:
marketing_data.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,2,5
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,6,5

In [4]:
# Remove duplicates across the columns in our dataset:
marketing_data_duplicate = marketing_data.drop_duplicates()
print(marketing_data.shape, '->', marketing_data_duplicate.shape)

(2240, 11) -> (2240, 11)

In [5]:
# Delete a specified row at index value 1:
marketing_data.drop(labels=[1], axis=0)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,6,5
5,7446,1967,Master,Together,62513.0,0,1,09-09-2013,16,10,6
...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,4,5
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,5,7
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,13,6
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,10,3
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,4,7

In [6]:
# Delete a single column
marketing_data.drop(labels=['Year_Birth'], axis=1)

,ID,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,NumStorePurchases,NumWebVisitsMonth
0,5524,Graduation,Single,58138.0,0,0,04-09-2012,58,4,7
1,2174,Graduation,Single,46344.0,1,1,08-03-2014,38,2,5
2,4141,Graduation,Together,71613.0,0,0,21-08-2013,26,10,4
3,6182,Graduation,Together,26646.0,1,0,10-02-2014,26,4,6
4,5324,PhD,Married,58293.0,1,0,19-01-2014,94,6,5
...,...,...,...,...,...,...,...,...,...,...
2235,10870,Graduation,Married,61223.0,0,1,13-06-2013,46,4,5
2236,4001,PhD,Together,64014.0,2,1,10-06-2014,56,5,7
2237,7270,Graduation,Divorced,56981.0,0,0,25-01-2014,91,13,6
2238,8235,Master,Together,69245.0,0,1,24-01-2014,8,10,3
2239,9405,PhD,Married,52869.0,1,1,15-10-2012,40,4,7

**3. Thay thế dữ liệu và thay đổi định dạng của dữ liệu**

In [7]:
# Replace the values in Teenhome with has teen and has no teen
marketing_data['Teenhome_replaced'] = marketing_data['Teenhome'].replace([0,1,2],['has no teen','has teen','has teen'])
marketing_data[['Teenhome','Teenhome_replaced']].head()

   Teenhome Teenhome_replaced
0         0       has no teen
1         1          has teen
2         0       has no teen
3         0       has no teen
4         0       has no teen

In [8]:
# Fill NAs in the Income column
marketing_data['Income'] = marketing_data['Income'].fillna(0)
# Change the data type of the Income column from float to int
marketing_data['Income_changed'] = marketing_data['Income'].astype(int)
marketing_data[['Income','Income_changed']].dtypes

Income            float64
Income_changed      int64
dtype: object

**4. Xử lý dữ liệu thiếu**

In [9]:
# Check for missing values using the isnull and sum methods
marketing_data.isnull().sum()

ID                   0
Year_Birth           0
Education            0
Marital_Status       0
Income               0
Kidhome              0
Teenhome             0
Dt_Customer          0
Recency              0
NumStorePurchases    0
NumWebVisitsMonth    0
Teenhome_replaced    0
Income_changed       0
dtype: int64

In [10]:
# Drop missing values using the dropna method
marketing_data_withoutna = marketing_data.dropna(how = 'any')
marketing_data_withoutna.shape

(2240, 13)

### Bài toán 3: công cụ EDA tự động
#### Nhiệm vụ 1: ydata_profiling (trước đây là pandas_profiling) trên dữ liệu Customer Personality Analysis

In [11]:
import pandas as pd
from ydata_profiling import ProfileReport
# [Chỉnh] sep='\t' cho đúng định dạng file Marketing Campaign
marketing_data = pd.read_csv("data/marketing_campaign.csv", sep='\t', encoding='utf-8-sig')
# Create an Automated EDA report using the ProfileReport class in the
# ydata_profiling library. Use the to_file method to output the report to an HTML file
profile = ProfileReport(marketing_data)
profile.to_file("Reports/profile_output.html")

/usr/local/lib/python3.12/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

/tmp/ipykernel_113/28472545.py:2: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Summarize dataset:   0%|          | 0/34 [00:00<?, ?it/s, Describe variable: ID]

  0%|          | 0/29 [00:00<?, ?it/s]

Summarize dataset:   3%|▎         | 1/34 [00:00<00:01, 16.79it/s, Describe variable: Year_Birth]

Summarize dataset:   6%|▌         | 2/34 [00:00<00:01, 21.84it/s, Describe variable: Education]

Summarize dataset:   9%|▉         | 3/34 [00:00<00:04,  7.23it/s, Describe variable: Education]

Summarize dataset:   9%|▉         | 3/34 [00:00<00:04,  7.23it/s, Describe variable: Marital_Status]

 10%|█         | 3/29 [00:00<00:03,  7.75it/s]

Summarize dataset:  12%|█▏        | 4/34 [00:00<00:04,  7.01it/s, Describe variable: Marital_Status]

Summarize dataset:  12%|█▏        | 4/34 [00:00<00:04,  7.01it/s, Describe variable: Income]

 14%|█▍        | 4/29 [00:00<00:03,  7.29it/s]

Summarize dataset:  15%|█▍        | 5/34 [00:00<00:04,  7.01it/s, Describe variable: Kidhome]

Summarize dataset:  18%|█▊        | 6/34 [00:00<00:03,  9.32it/s, Describe variable: Kidhome]

Summarize dataset:  18%|█▊        | 6/34 [00:00<00:03,  9.32it/s, Describe variable: Teenhome]

 21%|██        | 6/29 [00:00<00:02,  9.66it/s]

Summarize dataset:  21%|██        | 7/34 [00:00<00:02,  9.32it/s, Describe variable: Dt_Customer]

Summarize dataset:  24%|██▎       | 8/34 [00:00<00:03,  8.47it/s, Describe variable: Dt_Customer]

Summarize dataset:  24%|██▎       | 8/34 [00:00<00:03,  8.47it/s, Describe variable: Recency]

 28%|██▊       | 8/29 [00:00<00:02,  8.69it/s]

Summarize dataset:  26%|██▋       | 9/34 [00:01<00:02,  8.47it/s, Describe variable: MntWines]

Summarize dataset:  29%|██▉       | 10/34 [00:01<00:02,  8.47it/s, Describe variable: MntFruits]

Summarize dataset:  32%|███▏      | 11/34 [00:01<00:01, 12.28it/s, Describe variable: MntFruits]

Summarize dataset:  32%|███▏      | 11/34 [00:01<00:01, 12.28it/s, Describe variable: MntMeatProducts]

 38%|███▊      | 11/29 [00:01<00:01, 12.35it/s]

Summarize dataset:  35%|███▌      | 12/34 [00:01<00:01, 12.28it/s, Describe variable: MntFishProducts]

Summarize dataset:  38%|███▊      | 13/34 [00:01<00:01, 12.28it/s, Describe variable: MntSweetProducts]

Summarize dataset:  41%|████      | 14/34 [00:01<00:01, 15.52it/s, Describe variable: MntSweetProducts]

Summarize dataset:  41%|████      | 14/34 [00:01<00:01, 15.52it/s, Describe variable: MntGoldProds]

 48%|████▊     | 14/29 [00:01<00:00, 15.63it/s]

Summarize dataset:  44%|████▍     | 15/34 [00:01<00:01, 15.52it/s, Describe variable: NumDealsPurchases]

Summarize dataset:  47%|████▋     | 16/34 [00:01<00:01, 15.73it/s, Describe variable: NumDealsPurchases]

Summarize dataset:  47%|████▋     | 16/34 [00:01<00:01, 15.73it/s, Describe variable: NumWebPurchases]

 55%|█████▌    | 16/29 [00:01<00:00, 15.92it/s]

Summarize dataset:  50%|█████     | 17/34 [00:01<00:01, 15.73it/s, Describe variable: NumCatalogPurchases]

Summarize dataset:  53%|█████▎    | 18/34 [00:01<00:01, 15.72it/s, Describe variable: NumCatalogPurchases]

Summarize dataset:  53%|█████▎    | 18/34 [00:01<00:01, 15.72it/s, Describe variable: NumStorePurchases]

 62%|██████▏   | 18/29 [00:01<00:00, 15.83it/s]

Summarize dataset:  56%|█████▌    | 19/34 [00:01<00:00, 15.72it/s, Describe variable: NumWebVisitsMonth]

Summarize dataset:  59%|█████▉    | 20/34 [00:01<00:00, 15.82it/s, Describe variable: NumWebVisitsMonth]

Summarize dataset:  59%|█████▉    | 20/34 [00:01<00:00, 15.82it/s, Describe variable: AcceptedCmp3]

 69%|██████▉   | 20/29 [00:01<00:00, 15.92it/s]

Summarize dataset:  62%|██████▏   | 21/34 [00:01<00:00, 15.82it/s, Describe variable: AcceptedCmp4]

Summarize dataset:  65%|██████▍   | 22/34 [00:02<00:01,  7.10it/s, Describe variable: AcceptedCmp4]

Summarize dataset:  65%|██████▍   | 22/34 [00:02<00:01,  7.10it/s, Describe variable: AcceptedCmp5]

 76%|███████▌  | 22/29 [00:02<00:00,  7.16it/s]

Summarize dataset:  68%|██████▊   | 23/34 [00:02<00:01,  7.10it/s, Describe variable: AcceptedCmp1]

Summarize dataset:  71%|███████   | 24/34 [00:02<00:01,  8.18it/s, Describe variable: AcceptedCmp1]

Summarize dataset:  71%|███████   | 24/34 [00:02<00:01,  8.18it/s, Describe variable: AcceptedCmp2]

 83%|████████▎ | 24/29 [00:02<00:00,  8.22it/s]

Summarize dataset:  74%|███████▎  | 25/34 [00:02<00:01,  8.18it/s, Describe variable: Complain]

Summarize dataset:  76%|███████▋  | 26/34 [00:02<00:00,  8.82it/s, Describe variable: Complain]

Summarize dataset:  76%|███████▋  | 26/34 [00:02<00:00,  8.82it/s, Describe variable: Z_CostContact]

 90%|████████▉ | 26/29 [00:02<00:00,  8.87it/s]

Summarize dataset:  79%|███████▉  | 27/34 [00:02<00:00,  8.82it/s, Describe variable: Z_Revenue]

Summarize dataset:  82%|████████▏ | 28/34 [00:02<00:00, 10.27it/s, Describe variable: Z_Revenue]

Summarize dataset:  82%|████████▏ | 28/34 [00:02<00:00, 10.27it/s, Describe variable: Response]

 97%|█████████▋| 28/29 [00:02<00:00, 10.18it/s]

100%|██████████| 29/29 [00:02<00:00, 10.62it/s]

Summarize dataset:  85%|████████▌ | 29/34 [00:02<00:00, 10.27it/s, Get variable types]

Summarize dataset:  86%|████████▌ | 30/35 [00:02<00:00, 10.27it/s, Get dataframe statistics]

Summarize dataset:  86%|████████▌ | 31/36 [00:02<00:00, 10.27it/s, Calculate auto correlation]

Summarize dataset:  89%|████████▉ | 32/36 [00:09<00:03,  1.26it/s, Calculate auto correlation]

Summarize dataset:  89%|████████▉ | 32/36 [00:09<00:03,  1.26it/s, Get scatter matrix]

Summarize dataset:  12%|█▏        | 32/261 [00:09<03:02,  1.26it/s, scatter ID, ID]

Summarize dataset:  13%|█▎        | 33/261 [00:09<02:51,  1.33it/s, scatter ID, ID]

Summarize dataset:  13%|█▎        | 33/261 [00:09<02:51,  1.33it/s, scatter Year_Birth, ID]

Summarize dataset:  13%|█▎        | 34/261 [00:10<02:35,  1.46it/s, scatter Year_Birth, ID]

Summarize dataset:  13%|█▎        | 34/261 [00:10<02:35,  1.46it/s, scatter Income, ID]

Summarize dataset:  13%|█▎        | 35/261 [00:10<02:24,  1.57it/s, scatter Income, ID]

Summarize dataset:  13%|█▎        | 35/261 [00:10<02:24,  1.57it/s, scatter Recency, ID]

Summarize dataset:  14%|█▍        | 36/261 [00:10<02:14,  1.67it/s, scatter Recency, ID]

Summarize dataset:  14%|█▍        | 36/261 [00:10<02:14,  1.67it/s, scatter MntWines, ID]

Summarize dataset:  14%|█▍        | 37/261 [00:11<02:00,  1.85it/s, scatter MntWines, ID]

Summarize dataset:  14%|█▍        | 37/261 [00:11<02:00,  1.85it/s, scatter MntFruits, ID]

Summarize dataset:  15%|█▍        | 38/261 [00:11<01:54,  1.95it/s, scatter MntFruits, ID]

Summarize dataset:  15%|█▍        | 38/261 [00:11<01:54,  1.95it/s, scatter MntMeatProducts, ID]

Summarize dataset:  15%|█▍        | 39/261 [00:12<01:54,  1.94it/s, scatter MntMeatProducts, ID]

Summarize dataset:  15%|█▍        | 39/261 [00:12<01:54,  1.94it/s, scatter MntFishProducts, ID]

Summarize dataset:  15%|█▌        | 40/261 [00:12<01:48,  2.03it/s, scatter MntFishProducts, ID]

Summarize dataset:  15%|█▌        | 40/261 [00:12<01:48,  2.03it/s, scatter MntSweetProducts, ID]

Summarize dataset:  16%|█▌        | 41/261 [00:13<01:40,  2.19it/s, scatter MntSweetProducts, ID]

Summarize dataset:  16%|█▌        | 41/261 [00:13<01:40,  2.19it/s, scatter MntGoldProds, ID]

Summarize dataset:  16%|█▌        | 42/261 [00:13<01:38,  2.23it/s, scatter MntGoldProds, ID]

Summarize dataset:  16%|█▌        | 42/261 [00:13<01:38,  2.23it/s, scatter NumDealsPurchases, ID]

Summarize dataset:  16%|█▋        | 43/261 [00:13<01:37,  2.23it/s, scatter NumDealsPurchases, ID]

Summarize dataset:  16%|█▋        | 43/261 [00:13<01:37,  2.23it/s, scatter NumWebPurchases, ID]

Summarize dataset:  17%|█▋        | 44/261 [00:14<01:41,  2.13it/s, scatter NumWebPurchases, ID]

Summarize dataset:  17%|█▋        | 44/261 [00:14<01:41,  2.13it/s, scatter NumCatalogPurchases, ID]

Summarize dataset:  17%|█▋        | 45/261 [00:14<01:34,  2.27it/s, scatter NumCatalogPurchases, ID]

Summarize dataset:  17%|█▋        | 45/261 [00:14<01:34,  2.27it/s, scatter NumStorePurchases, ID]

Summarize dataset:  18%|█▊        | 46/261 [00:15<01:30,  2.39it/s, scatter NumStorePurchases, ID]

Summarize dataset:  18%|█▊        | 46/261 [00:15<01:30,  2.39it/s, scatter NumWebVisitsMonth, ID]

Summarize dataset:  18%|█▊        | 47/261 [00:15<01:27,  2.45it/s, scatter NumWebVisitsMonth, ID]

Summarize dataset:  18%|█▊        | 47/261 [00:15<01:27,  2.45it/s, scatter ID, Year_Birth]

Summarize dataset:  18%|█▊        | 48/261 [00:15<01:23,  2.55it/s, scatter ID, Year_Birth]

Summarize dataset:  18%|█▊        | 48/261 [00:15<01:23,  2.55it/s, scatter Year_Birth, Year_Birth]

Summarize dataset:  19%|█▉        | 49/261 [00:16<01:24,  2.51it/s, scatter Year_Birth, Year_Birth]

Summarize dataset:  19%|█▉        | 49/261 [00:16<01:24,  2.51it/s, scatter Income, Year_Birth]

Summarize dataset:  19%|█▉        | 50/261 [00:16<01:29,  2.37it/s, scatter Income, Year_Birth]

Summarize dataset:  19%|█▉        | 50/261 [00:16<01:29,  2.37it/s, scatter Recency, Year_Birth]

Summarize dataset:  20%|█▉        | 51/261 [00:17<01:29,  2.34it/s, scatter Recency, Year_Birth]

Summarize dataset:  20%|█▉        | 51/261 [00:17<01:29,  2.34it/s, scatter MntWines, Year_Birth]

Summarize dataset:  20%|█▉        | 52/261 [00:17<01:23,  2.51it/s, scatter MntWines, Year_Birth]

Summarize dataset:  20%|█▉        | 52/261 [00:17<01:23,  2.51it/s, scatter MntFruits, Year_Birth]

Summarize dataset:  20%|██        | 53/261 [00:17<01:16,  2.72it/s, scatter MntFruits, Year_Birth]

Summarize dataset:  20%|██        | 53/261 [00:17<01:16,  2.72it/s, scatter MntMeatProducts, Year_Birth]

Summarize dataset:  21%|██        | 54/261 [00:18<01:14,  2.79it/s, scatter MntMeatProducts, Year_Birth]

Summarize dataset:  21%|██        | 54/261 [00:18<01:14,  2.79it/s, scatter MntFishProducts, Year_Birth]

Summarize dataset:  21%|██        | 55/261 [00:18<01:08,  3.02it/s, scatter MntFishProducts, Year_Birth]

Summarize dataset:  21%|██        | 55/261 [00:18<01:08,  3.02it/s, scatter MntSweetProducts, Year_Birth]

Summarize dataset:  21%|██▏       | 56/261 [00:18<01:03,  3.24it/s, scatter MntSweetProducts, Year_Birth]

Summarize dataset:  21%|██▏       | 56/261 [00:18<01:03,  3.24it/s, scatter MntGoldProds, Year_Birth]

Summarize dataset:  22%|██▏       | 57/261 [00:18<01:00,  3.36it/s, scatter MntGoldProds, Year_Birth]

Summarize dataset:  22%|██▏       | 57/261 [00:18<01:00,  3.36it/s, scatter NumDealsPurchases, Year_Birth]

Summarize dataset:  22%|██▏       | 58/261 [00:19<00:56,  3.59it/s, scatter NumDealsPurchases, Year_Birth]

Summarize dataset:  22%|██▏       | 58/261 [00:19<00:56,  3.59it/s, scatter NumWebPurchases, Year_Birth]

Summarize dataset:  23%|██▎       | 59/261 [00:19<01:01,  3.28it/s, scatter NumWebPurchases, Year_Birth]

Summarize dataset:  23%|██▎       | 59/261 [00:19<01:01,  3.28it/s, scatter NumCatalogPurchases, Year_Birth]

Summarize dataset:  23%|██▎       | 60/261 [00:19<01:02,  3.20it/s, scatter NumCatalogPurchases, Year_Birth]

Summarize dataset:  23%|██▎       | 60/261 [00:19<01:02,  3.20it/s, scatter NumStorePurchases, Year_Birth]

Summarize dataset:  23%|██▎       | 61/261 [00:20<01:05,  3.05it/s, scatter NumStorePurchases, Year_Birth]

Summarize dataset:  23%|██▎       | 61/261 [00:20<01:05,  3.05it/s, scatter NumWebVisitsMonth, Year_Birth]

Summarize dataset:  24%|██▍       | 62/261 [00:20<01:09,  2.86it/s, scatter NumWebVisitsMonth, Year_Birth]

Summarize dataset:  24%|██▍       | 62/261 [00:20<01:09,  2.86it/s, scatter ID, Income]

Summarize dataset:  24%|██▍       | 63/261 [00:21<01:11,  2.76it/s, scatter ID, Income]

Summarize dataset:  24%|██▍       | 63/261 [00:21<01:11,  2.76it/s, scatter Year_Birth, Income]

Summarize dataset:  25%|██▍       | 64/261 [00:21<01:14,  2.64it/s, scatter Year_Birth, Income]

Summarize dataset:  25%|██▍       | 64/261 [00:21<01:14,  2.64it/s, scatter Income, Income]

Summarize dataset:  25%|██▍       | 65/261 [00:21<01:16,  2.58it/s, scatter Income, Income]

Summarize dataset:  25%|██▍       | 65/261 [00:21<01:16,  2.58it/s, scatter Recency, Income]

Summarize dataset:  25%|██▌       | 66/261 [00:22<01:16,  2.56it/s, scatter Recency, Income]

Summarize dataset:  25%|██▌       | 66/261 [00:22<01:16,  2.56it/s, scatter MntWines, Income]

Summarize dataset:  26%|██▌       | 67/261 [00:22<01:14,  2.61it/s, scatter MntWines, Income]

Summarize dataset:  26%|██▌       | 67/261 [00:22<01:14,  2.61it/s, scatter MntFruits, Income]

Summarize dataset:  26%|██▌       | 68/261 [00:23<01:13,  2.62it/s, scatter MntFruits, Income]

Summarize dataset:  26%|██▌       | 68/261 [00:23<01:13,  2.62it/s, scatter MntMeatProducts, Income]

Summarize dataset:  26%|██▋       | 69/261 [00:23<01:14,  2.56it/s, scatter MntMeatProducts, Income]

Summarize dataset:  26%|██▋       | 69/261 [00:23<01:14,  2.56it/s, scatter MntFishProducts, Income]

Summarize dataset:  27%|██▋       | 70/261 [00:24<02:03,  1.54it/s, scatter MntFishProducts, Income]

Summarize dataset:  27%|██▋       | 70/261 [00:24<02:03,  1.54it/s, scatter MntSweetProducts, Income]

Summarize dataset:  27%|██▋       | 71/261 [00:25<01:49,  1.74it/s, scatter MntSweetProducts, Income]

Summarize dataset:  27%|██▋       | 71/261 [00:25<01:49,  1.74it/s, scatter MntGoldProds, Income]

Summarize dataset:  28%|██▊       | 72/261 [00:25<01:39,  1.89it/s, scatter MntGoldProds, Income]

Summarize dataset:  28%|██▊       | 72/261 [00:25<01:39,  1.89it/s, scatter NumDealsPurchases, Income]

Summarize dataset:  28%|██▊       | 73/261 [00:25<01:32,  2.04it/s, scatter NumDealsPurchases, Income]

Summarize dataset:  28%|██▊       | 73/261 [00:25<01:32,  2.04it/s, scatter NumWebPurchases, Income]

Summarize dataset:  28%|██▊       | 74/261 [00:26<01:24,  2.21it/s, scatter NumWebPurchases, Income]

Summarize dataset:  28%|██▊       | 74/261 [00:26<01:24,  2.21it/s, scatter NumCatalogPurchases, Income]

Summarize dataset:  29%|██▊       | 75/261 [00:26<01:19,  2.35it/s, scatter NumCatalogPurchases, Income]

Summarize dataset:  29%|██▊       | 75/261 [00:26<01:19,  2.35it/s, scatter NumStorePurchases, Income]

Summarize dataset:  29%|██▉       | 76/261 [00:27<01:15,  2.44it/s, scatter NumStorePurchases, Income]

Summarize dataset:  29%|██▉       | 76/261 [00:27<01:15,  2.44it/s, scatter NumWebVisitsMonth, Income]

Summarize dataset:  30%|██▉       | 77/261 [00:27<01:19,  2.31it/s, scatter NumWebVisitsMonth, Income]

Summarize dataset:  30%|██▉       | 77/261 [00:27<01:19,  2.31it/s, scatter ID, Recency]

Summarize dataset:  30%|██▉       | 78/261 [00:27<01:17,  2.35it/s, scatter ID, Recency]

Summarize dataset:  30%|██▉       | 78/261 [00:27<01:17,  2.35it/s, scatter Year_Birth, Recency]

Summarize dataset:  30%|███       | 79/261 [00:28<01:15,  2.40it/s, scatter Year_Birth, Recency]

Summarize dataset:  30%|███       | 79/261 [00:28<01:15,  2.40it/s, scatter Income, Recency]

Summarize dataset:  31%|███       | 80/261 [00:28<01:16,  2.38it/s, scatter Income, Recency]

Summarize dataset:  31%|███       | 80/261 [00:28<01:16,  2.38it/s, scatter Recency, Recency]

Summarize dataset:  31%|███       | 81/261 [00:29<01:11,  2.51it/s, scatter Recency, Recency]

Summarize dataset:  31%|███       | 81/261 [00:29<01:11,  2.51it/s, scatter MntWines, Recency]

Summarize dataset:  31%|███▏      | 82/261 [00:29<01:12,  2.48it/s, scatter MntWines, Recency]

Summarize dataset:  31%|███▏      | 82/261 [00:29<01:12,  2.48it/s, scatter MntFruits, Recency]

Summarize dataset:  32%|███▏      | 83/261 [00:29<01:09,  2.56it/s, scatter MntFruits, Recency]

Summarize dataset:  32%|███▏      | 83/261 [00:29<01:09,  2.56it/s, scatter MntMeatProducts, Recency]

Summarize dataset:  32%|███▏      | 84/261 [00:30<01:09,  2.55it/s, scatter MntMeatProducts, Recency]

Summarize dataset:  32%|███▏      | 84/261 [00:30<01:09,  2.55it/s, scatter MntFishProducts, Recency]

Summarize dataset:  33%|███▎      | 85/261 [00:30<01:11,  2.46it/s, scatter MntFishProducts, Recency]

Summarize dataset:  33%|███▎      | 85/261 [00:30<01:11,  2.46it/s, scatter MntSweetProducts, Recency]

Summarize dataset:  33%|███▎      | 86/261 [00:31<01:10,  2.49it/s, scatter MntSweetProducts, Recency]

Summarize dataset:  33%|███▎      | 86/261 [00:31<01:10,  2.49it/s, scatter MntGoldProds, Recency]

Summarize dataset:  33%|███▎      | 87/261 [00:31<01:08,  2.52it/s, scatter MntGoldProds, Recency]

Summarize dataset:  33%|███▎      | 87/261 [00:31<01:08,  2.52it/s, scatter NumDealsPurchases, Recency]

Summarize dataset:  34%|███▎      | 88/261 [00:31<01:11,  2.41it/s, scatter NumDealsPurchases, Recency]

Summarize dataset:  34%|███▎      | 88/261 [00:31<01:11,  2.41it/s, scatter NumWebPurchases, Recency]

Summarize dataset:  34%|███▍      | 89/261 [00:32<01:09,  2.47it/s, scatter NumWebPurchases, Recency]

Summarize dataset:  34%|███▍      | 89/261 [00:32<01:09,  2.47it/s, scatter NumCatalogPurchases, Recency]

Summarize dataset:  34%|███▍      | 90/261 [00:32<01:12,  2.37it/s, scatter NumCatalogPurchases, Recency]

Summarize dataset:  34%|███▍      | 90/261 [00:32<01:12,  2.37it/s, scatter NumStorePurchases, Recency]

Summarize dataset:  35%|███▍      | 91/261 [00:33<01:15,  2.26it/s, scatter NumStorePurchases, Recency]

Summarize dataset:  35%|███▍      | 91/261 [00:33<01:15,  2.26it/s, scatter NumWebVisitsMonth, Recency]

Summarize dataset:  35%|███▌      | 92/261 [00:33<01:14,  2.27it/s, scatter NumWebVisitsMonth, Recency]

Summarize dataset:  35%|███▌      | 92/261 [00:33<01:14,  2.27it/s, scatter ID, MntWines]

Summarize dataset:  36%|███▌      | 93/261 [00:34<01:14,  2.24it/s, scatter ID, MntWines]

Summarize dataset:  36%|███▌      | 93/261 [00:34<01:14,  2.24it/s, scatter Year_Birth, MntWines]

Summarize dataset:  36%|███▌      | 94/261 [00:34<01:19,  2.09it/s, scatter Year_Birth, MntWines]

Summarize dataset:  36%|███▌      | 94/261 [00:34<01:19,  2.09it/s, scatter Income, MntWines]

Summarize dataset:  36%|███▋      | 95/261 [00:35<01:17,  2.13it/s, scatter Income, MntWines]

Summarize dataset:  36%|███▋      | 95/261 [00:35<01:17,  2.13it/s, scatter Recency, MntWines]

Summarize dataset:  37%|███▋      | 96/261 [00:35<01:15,  2.18it/s, scatter Recency, MntWines]

Summarize dataset:  37%|███▋      | 96/261 [00:35<01:15,  2.18it/s, scatter MntWines, MntWines]

Summarize dataset:  37%|███▋      | 97/261 [00:35<01:11,  2.30it/s, scatter MntWines, MntWines]

Summarize dataset:  37%|███▋      | 97/261 [00:35<01:11,  2.30it/s, scatter MntFruits, MntWines]

Summarize dataset:  38%|███▊      | 98/261 [00:36<01:08,  2.36it/s, scatter MntFruits, MntWines]

Summarize dataset:  38%|███▊      | 98/261 [00:36<01:08,  2.36it/s, scatter MntMeatProducts, MntWines]

Summarize dataset:  38%|███▊      | 99/261 [00:36<01:06,  2.45it/s, scatter MntMeatProducts, MntWines]

Summarize dataset:  38%|███▊      | 99/261 [00:36<01:06,  2.45it/s, scatter MntFishProducts, MntWines]

Summarize dataset:  38%|███▊      | 100/261 [00:37<01:08,  2.35it/s, scatter MntFishProducts, MntWines]

Summarize dataset:  38%|███▊      | 100/261 [00:37<01:08,  2.35it/s, scatter MntSweetProducts, MntWines]

Summarize dataset:  39%|███▊      | 101/261 [00:37<01:08,  2.33it/s, scatter MntSweetProducts, MntWines]

Summarize dataset:  39%|███▊      | 101/261 [00:37<01:08,  2.33it/s, scatter MntGoldProds, MntWines]

Summarize dataset:  39%|███▉      | 102/261 [00:38<01:06,  2.39it/s, scatter MntGoldProds, MntWines]

Summarize dataset:  39%|███▉      | 102/261 [00:38<01:06,  2.39it/s, scatter NumDealsPurchases, MntWines]

Summarize dataset:  39%|███▉      | 103/261 [00:38<01:06,  2.39it/s, scatter NumDealsPurchases, MntWines]

Summarize dataset:  39%|███▉      | 103/261 [00:38<01:06,  2.39it/s, scatter NumWebPurchases, MntWines]

Summarize dataset:  40%|███▉      | 104/261 [00:38<01:03,  2.46it/s, scatter NumWebPurchases, MntWines]

Summarize dataset:  40%|███▉      | 104/261 [00:38<01:03,  2.46it/s, scatter NumCatalogPurchases, MntWines]

Summarize dataset:  40%|████      | 105/261 [00:39<01:03,  2.46it/s, scatter NumCatalogPurchases, MntWines]

Summarize dataset:  40%|████      | 105/261 [00:39<01:03,  2.46it/s, scatter NumStorePurchases, MntWines]

Summarize dataset:  41%|████      | 106/261 [00:39<01:02,  2.48it/s, scatter NumStorePurchases, MntWines]

Summarize dataset:  41%|████      | 106/261 [00:39<01:02,  2.48it/s, scatter NumWebVisitsMonth, MntWines]

Summarize dataset:  41%|████      | 107/261 [00:40<01:00,  2.53it/s, scatter NumWebVisitsMonth, MntWines]

Summarize dataset:  41%|████      | 107/261 [00:40<01:00,  2.53it/s, scatter ID, MntFruits]

Summarize dataset:  41%|████▏     | 108/261 [00:40<00:59,  2.59it/s, scatter ID, MntFruits]

Summarize dataset:  41%|████▏     | 108/261 [00:40<00:59,  2.59it/s, scatter Year_Birth, MntFruits]

Summarize dataset:  42%|████▏     | 109/261 [00:40<00:59,  2.56it/s, scatter Year_Birth, MntFruits]

Summarize dataset:  42%|████▏     | 109/261 [00:40<00:59,  2.56it/s, scatter Income, MntFruits]

Summarize dataset:  42%|████▏     | 110/261 [00:42<01:56,  1.30it/s, scatter Income, MntFruits]

Summarize dataset:  42%|████▏     | 110/261 [00:42<01:56,  1.30it/s, scatter Recency, MntFruits]

Summarize dataset:  43%|████▎     | 111/261 [00:42<01:40,  1.49it/s, scatter Recency, MntFruits]

Summarize dataset:  43%|████▎     | 111/261 [00:42<01:40,  1.49it/s, scatter MntWines, MntFruits]

Summarize dataset:  43%|████▎     | 112/261 [00:43<01:28,  1.68it/s, scatter MntWines, MntFruits]

Summarize dataset:  43%|████▎     | 112/261 [00:43<01:28,  1.68it/s, scatter MntFruits, MntFruits]

Summarize dataset:  43%|████▎     | 113/261 [00:43<01:19,  1.85it/s, scatter MntFruits, MntFruits]

Summarize dataset:  43%|████▎     | 113/261 [00:43<01:19,  1.85it/s, scatter MntMeatProducts, MntFruits]

Summarize dataset:  44%|████▎     | 114/261 [00:44<01:13,  2.00it/s, scatter MntMeatProducts, MntFruits]

Summarize dataset:  44%|████▎     | 114/261 [00:44<01:13,  2.00it/s, scatter MntFishProducts, MntFruits]

Summarize dataset:  44%|████▍     | 115/261 [00:44<01:09,  2.10it/s, scatter MntFishProducts, MntFruits]

Summarize dataset:  44%|████▍     | 115/261 [00:44<01:09,  2.10it/s, scatter MntSweetProducts, MntFruits]

Summarize dataset:  44%|████▍     | 116/261 [00:44<01:07,  2.14it/s, scatter MntSweetProducts, MntFruits]

Summarize dataset:  44%|████▍     | 116/261 [00:44<01:07,  2.14it/s, scatter MntGoldProds, MntFruits]

Summarize dataset:  45%|████▍     | 117/261 [00:45<01:04,  2.23it/s, scatter MntGoldProds, MntFruits]

Summarize dataset:  45%|████▍     | 117/261 [00:45<01:04,  2.23it/s, scatter NumDealsPurchases, MntFruits]

Summarize dataset:  45%|████▌     | 118/261 [00:45<01:01,  2.32it/s, scatter NumDealsPurchases, MntFruits]

Summarize dataset:  45%|████▌     | 118/261 [00:45<01:01,  2.32it/s, scatter NumWebPurchases, MntFruits]

Summarize dataset:  46%|████▌     | 119/261 [00:46<00:58,  2.41it/s, scatter NumWebPurchases, MntFruits]

Summarize dataset:  46%|████▌     | 119/261 [00:46<00:58,  2.41it/s, scatter NumCatalogPurchases, MntFruits]

Summarize dataset:  46%|████▌     | 120/261 [00:46<00:59,  2.39it/s, scatter NumCatalogPurchases, MntFruits]

Summarize dataset:  46%|████▌     | 120/261 [00:46<00:59,  2.39it/s, scatter NumStorePurchases, MntFruits]

Summarize dataset:  46%|████▋     | 121/261 [00:47<01:00,  2.30it/s, scatter NumStorePurchases, MntFruits]

Summarize dataset:  46%|████▋     | 121/261 [00:47<01:00,  2.30it/s, scatter NumWebVisitsMonth, MntFruits]

Summarize dataset:  47%|████▋     | 122/261 [00:47<01:01,  2.26it/s, scatter NumWebVisitsMonth, MntFruits]

Summarize dataset:  47%|████▋     | 122/261 [00:47<01:01,  2.26it/s, scatter ID, MntMeatProducts]

Summarize dataset:  47%|████▋     | 123/261 [00:47<00:58,  2.34it/s, scatter ID, MntMeatProducts]

Summarize dataset:  47%|████▋     | 123/261 [00:47<00:58,  2.34it/s, scatter Year_Birth, MntMeatProducts]

Summarize dataset:  48%|████▊     | 124/261 [00:48<00:59,  2.32it/s, scatter Year_Birth, MntMeatProducts]

Summarize dataset:  48%|████▊     | 124/261 [00:48<00:59,  2.32it/s, scatter Income, MntMeatProducts]

Summarize dataset:  48%|████▊     | 125/261 [00:48<00:59,  2.29it/s, scatter Income, MntMeatProducts]

Summarize dataset:  48%|████▊     | 125/261 [00:48<00:59,  2.29it/s, scatter Recency, MntMeatProducts]

Summarize dataset:  48%|████▊     | 126/261 [00:49<00:57,  2.36it/s, scatter Recency, MntMeatProducts]

Summarize dataset:  48%|████▊     | 126/261 [00:49<00:57,  2.36it/s, scatter MntWines, MntMeatProducts]

Summarize dataset:  49%|████▊     | 127/261 [00:49<00:56,  2.36it/s, scatter MntWines, MntMeatProducts]

Summarize dataset:  49%|████▊     | 127/261 [00:49<00:56,  2.36it/s, scatter MntFruits, MntMeatProducts]

Summarize dataset:  49%|████▉     | 128/261 [00:50<01:01,  2.17it/s, scatter MntFruits, MntMeatProducts]

Summarize dataset:  49%|████▉     | 128/261 [00:50<01:01,  2.17it/s, scatter MntMeatProducts, MntMeatProducts]

Summarize dataset:  49%|████▉     | 129/261 [00:50<00:59,  2.21it/s, scatter MntMeatProducts, MntMeatProducts]

Summarize dataset:  49%|████▉     | 129/261 [00:50<00:59,  2.21it/s, scatter MntFishProducts, MntMeatProducts]

Summarize dataset:  50%|████▉     | 130/261 [00:50<00:57,  2.29it/s, scatter MntFishProducts, MntMeatProducts]

Summarize dataset:  50%|████▉     | 130/261 [00:50<00:57,  2.29it/s, scatter MntSweetProducts, MntMeatProducts]

Summarize dataset:  50%|█████     | 131/261 [00:51<00:54,  2.40it/s, scatter MntSweetProducts, MntMeatProducts]

Summarize dataset:  50%|█████     | 131/261 [00:51<00:54,  2.40it/s, scatter MntGoldProds, MntMeatProducts]

Summarize dataset:  51%|█████     | 132/261 [00:51<00:53,  2.43it/s, scatter MntGoldProds, MntMeatProducts]

Summarize dataset:  51%|█████     | 132/261 [00:51<00:53,  2.43it/s, scatter NumDealsPurchases, MntMeatProducts]

Summarize dataset:  51%|█████     | 133/261 [00:52<00:51,  2.48it/s, scatter NumDealsPurchases, MntMeatProducts]

Summarize dataset:  51%|█████     | 133/261 [00:52<00:51,  2.48it/s, scatter NumWebPurchases, MntMeatProducts]

Summarize dataset:  51%|█████▏    | 134/261 [00:52<00:50,  2.52it/s, scatter NumWebPurchases, MntMeatProducts]

Summarize dataset:  51%|█████▏    | 134/261 [00:52<00:50,  2.52it/s, scatter NumCatalogPurchases, MntMeatProducts]

Summarize dataset:  52%|█████▏    | 135/261 [00:52<00:50,  2.47it/s, scatter NumCatalogPurchases, MntMeatProducts]

Summarize dataset:  52%|█████▏    | 135/261 [00:52<00:50,  2.47it/s, scatter NumStorePurchases, MntMeatProducts]

Summarize dataset:  52%|█████▏    | 136/261 [00:53<00:51,  2.45it/s, scatter NumStorePurchases, MntMeatProducts]

Summarize dataset:  52%|█████▏    | 136/261 [00:53<00:51,  2.45it/s, scatter NumWebVisitsMonth, MntMeatProducts]

Summarize dataset:  52%|█████▏    | 137/261 [00:53<00:51,  2.40it/s, scatter NumWebVisitsMonth, MntMeatProducts]

Summarize dataset:  52%|█████▏    | 137/261 [00:53<00:51,  2.40it/s, scatter ID, MntFishProducts]

Summarize dataset:  53%|█████▎    | 138/261 [00:54<00:50,  2.43it/s, scatter ID, MntFishProducts]

Summarize dataset:  53%|█████▎    | 138/261 [00:54<00:50,  2.43it/s, scatter Year_Birth, MntFishProducts]

Summarize dataset:  53%|█████▎    | 139/261 [00:54<00:51,  2.38it/s, scatter Year_Birth, MntFishProducts]

Summarize dataset:  53%|█████▎    | 139/261 [00:54<00:51,  2.38it/s, scatter Income, MntFishProducts]

Summarize dataset:  54%|█████▎    | 140/261 [00:55<00:49,  2.46it/s, scatter Income, MntFishProducts]

Summarize dataset:  54%|█████▎    | 140/261 [00:55<00:49,  2.46it/s, scatter Recency, MntFishProducts]

Summarize dataset:  54%|█████▍    | 141/261 [00:55<00:48,  2.50it/s, scatter Recency, MntFishProducts]

Summarize dataset:  54%|█████▍    | 141/261 [00:55<00:48,  2.50it/s, scatter MntWines, MntFishProducts]

Summarize dataset:  54%|█████▍    | 142/261 [00:55<00:46,  2.57it/s, scatter MntWines, MntFishProducts]

Summarize dataset:  54%|█████▍    | 142/261 [00:55<00:46,  2.57it/s, scatter MntFruits, MntFishProducts]

Summarize dataset:  55%|█████▍    | 143/261 [00:56<00:44,  2.67it/s, scatter MntFruits, MntFishProducts]

Summarize dataset:  55%|█████▍    | 143/261 [00:56<00:44,  2.67it/s, scatter MntMeatProducts, MntFishProducts]

Summarize dataset:  55%|█████▌    | 144/261 [00:56<00:43,  2.71it/s, scatter MntMeatProducts, MntFishProducts]

Summarize dataset:  55%|█████▌    | 144/261 [00:56<00:43,  2.71it/s, scatter MntFishProducts, MntFishProducts]

Summarize dataset:  56%|█████▌    | 145/261 [00:56<00:41,  2.82it/s, scatter MntFishProducts, MntFishProducts]

Summarize dataset:  56%|█████▌    | 145/261 [00:56<00:41,  2.82it/s, scatter MntSweetProducts, MntFishProducts]

Summarize dataset:  56%|█████▌    | 146/261 [00:57<00:41,  2.77it/s, scatter MntSweetProducts, MntFishProducts]

Summarize dataset:  56%|█████▌    | 146/261 [00:57<00:41,  2.77it/s, scatter MntGoldProds, MntFishProducts]

Summarize dataset:  56%|█████▋    | 147/261 [00:58<01:14,  1.54it/s, scatter MntGoldProds, MntFishProducts]

Summarize dataset:  56%|█████▋    | 147/261 [00:58<01:14,  1.54it/s, scatter NumDealsPurchases, MntFishProducts]

Summarize dataset:  57%|█████▋    | 148/261 [00:58<01:04,  1.76it/s, scatter NumDealsPurchases, MntFishProducts]

Summarize dataset:  57%|█████▋    | 148/261 [00:58<01:04,  1.76it/s, scatter NumWebPurchases, MntFishProducts]

Summarize dataset:  57%|█████▋    | 149/261 [00:59<00:55,  2.00it/s, scatter NumWebPurchases, MntFishProducts]

Summarize dataset:  57%|█████▋    | 149/261 [00:59<00:55,  2.00it/s, scatter NumCatalogPurchases, MntFishProducts]

Summarize dataset:  57%|█████▋    | 150/261 [00:59<00:51,  2.15it/s, scatter NumCatalogPurchases, MntFishProducts]

Summarize dataset:  57%|█████▋    | 150/261 [00:59<00:51,  2.15it/s, scatter NumStorePurchases, MntFishProducts]

Summarize dataset:  58%|█████▊    | 151/261 [00:59<00:48,  2.27it/s, scatter NumStorePurchases, MntFishProducts]

Summarize dataset:  58%|█████▊    | 151/261 [00:59<00:48,  2.27it/s, scatter NumWebVisitsMonth, MntFishProducts]

Summarize dataset:  58%|█████▊    | 152/261 [01:00<00:49,  2.21it/s, scatter NumWebVisitsMonth, MntFishProducts]

Summarize dataset:  58%|█████▊    | 152/261 [01:00<00:49,  2.21it/s, scatter ID, MntSweetProducts]

Summarize dataset:  59%|█████▊    | 153/261 [01:00<00:45,  2.38it/s, scatter ID, MntSweetProducts]

Summarize dataset:  59%|█████▊    | 153/261 [01:00<00:45,  2.38it/s, scatter Year_Birth, MntSweetProducts]

Summarize dataset:  59%|█████▉    | 154/261 [01:01<00:42,  2.51it/s, scatter Year_Birth, MntSweetProducts]

Summarize dataset:  59%|█████▉    | 154/261 [01:01<00:42,  2.51it/s, scatter Income, MntSweetProducts]

Summarize dataset:  59%|█████▉    | 155/261 [01:01<00:40,  2.64it/s, scatter Income, MntSweetProducts]

Summarize dataset:  59%|█████▉    | 155/261 [01:01<00:40,  2.64it/s, scatter Recency, MntSweetProducts]

Summarize dataset:  60%|█████▉    | 156/261 [01:01<00:38,  2.72it/s, scatter Recency, MntSweetProducts]

Summarize dataset:  60%|█████▉    | 156/261 [01:01<00:38,  2.72it/s, scatter MntWines, MntSweetProducts]

Summarize dataset:  60%|██████    | 157/261 [01:02<00:39,  2.60it/s, scatter MntWines, MntSweetProducts]

Summarize dataset:  60%|██████    | 157/261 [01:02<00:39,  2.60it/s, scatter MntFruits, MntSweetProducts]

Summarize dataset:  61%|██████    | 158/261 [01:02<00:41,  2.47it/s, scatter MntFruits, MntSweetProducts]

Summarize dataset:  61%|██████    | 158/261 [01:02<00:41,  2.47it/s, scatter MntMeatProducts, MntSweetProducts]

Summarize dataset:  61%|██████    | 159/261 [01:03<00:41,  2.48it/s, scatter MntMeatProducts, MntSweetProducts]

Summarize dataset:  61%|██████    | 159/261 [01:03<00:41,  2.48it/s, scatter MntFishProducts, MntSweetProducts]

Summarize dataset:  61%|██████▏   | 160/261 [01:03<00:41,  2.44it/s, scatter MntFishProducts, MntSweetProducts]

Summarize dataset:  61%|██████▏   | 160/261 [01:03<00:41,  2.44it/s, scatter MntSweetProducts, MntSweetProducts]

Summarize dataset:  62%|██████▏   | 161/261 [01:03<00:42,  2.38it/s, scatter MntSweetProducts, MntSweetProducts]

Summarize dataset:  62%|██████▏   | 161/261 [01:03<00:42,  2.38it/s, scatter MntGoldProds, MntSweetProducts]

Summarize dataset:  62%|██████▏   | 162/261 [01:04<00:39,  2.48it/s, scatter MntGoldProds, MntSweetProducts]

Summarize dataset:  62%|██████▏   | 162/261 [01:04<00:39,  2.48it/s, scatter NumDealsPurchases, MntSweetProducts]

Summarize dataset:  62%|██████▏   | 163/261 [01:04<00:38,  2.52it/s, scatter NumDealsPurchases, MntSweetProducts]

Summarize dataset:  62%|██████▏   | 163/261 [01:04<00:38,  2.52it/s, scatter NumWebPurchases, MntSweetProducts]

Summarize dataset:  63%|██████▎   | 164/261 [01:05<00:37,  2.56it/s, scatter NumWebPurchases, MntSweetProducts]

Summarize dataset:  63%|██████▎   | 164/261 [01:05<00:37,  2.56it/s, scatter NumCatalogPurchases, MntSweetProducts]

Summarize dataset:  63%|██████▎   | 165/261 [01:05<00:38,  2.51it/s, scatter NumCatalogPurchases, MntSweetProducts]

Summarize dataset:  63%|██████▎   | 165/261 [01:05<00:38,  2.51it/s, scatter NumStorePurchases, MntSweetProducts]

Summarize dataset:  64%|██████▎   | 166/261 [01:05<00:38,  2.46it/s, scatter NumStorePurchases, MntSweetProducts]

Summarize dataset:  64%|██████▎   | 166/261 [01:05<00:38,  2.46it/s, scatter NumWebVisitsMonth, MntSweetProducts]

Summarize dataset:  64%|██████▍   | 167/261 [01:06<00:41,  2.28it/s, scatter NumWebVisitsMonth, MntSweetProducts]

Summarize dataset:  64%|██████▍   | 167/261 [01:06<00:41,  2.28it/s, scatter ID, MntGoldProds]

Summarize dataset:  64%|██████▍   | 168/261 [01:06<00:39,  2.36it/s, scatter ID, MntGoldProds]

Summarize dataset:  64%|██████▍   | 168/261 [01:06<00:39,  2.36it/s, scatter Year_Birth, MntGoldProds]

Summarize dataset:  65%|██████▍   | 169/261 [01:07<00:44,  2.08it/s, scatter Year_Birth, MntGoldProds]

Summarize dataset:  65%|██████▍   | 169/261 [01:07<00:44,  2.08it/s, scatter Income, MntGoldProds]

Summarize dataset:  65%|██████▌   | 170/261 [01:07<00:41,  2.20it/s, scatter Income, MntGoldProds]

Summarize dataset:  65%|██████▌   | 170/261 [01:07<00:41,  2.20it/s, scatter Recency, MntGoldProds]

Summarize dataset:  66%|██████▌   | 171/261 [01:08<00:39,  2.25it/s, scatter Recency, MntGoldProds]

Summarize dataset:  66%|██████▌   | 171/261 [01:08<00:39,  2.25it/s, scatter MntWines, MntGoldProds]

Summarize dataset:  66%|██████▌   | 172/261 [01:08<00:39,  2.25it/s, scatter MntWines, MntGoldProds]

Summarize dataset:  66%|██████▌   | 172/261 [01:08<00:39,  2.25it/s, scatter MntFruits, MntGoldProds]

Summarize dataset:  66%|██████▋   | 173/261 [01:09<00:38,  2.26it/s, scatter MntFruits, MntGoldProds]

Summarize dataset:  66%|██████▋   | 173/261 [01:09<00:38,  2.26it/s, scatter MntMeatProducts, MntGoldProds]

Summarize dataset:  67%|██████▋   | 174/261 [01:09<00:40,  2.15it/s, scatter MntMeatProducts, MntGoldProds]

Summarize dataset:  67%|██████▋   | 174/261 [01:09<00:40,  2.15it/s, scatter MntFishProducts, MntGoldProds]

Summarize dataset:  67%|██████▋   | 175/261 [01:10<00:38,  2.23it/s, scatter MntFishProducts, MntGoldProds]

Summarize dataset:  67%|██████▋   | 175/261 [01:10<00:38,  2.23it/s, scatter MntSweetProducts, MntGoldProds]

Summarize dataset:  67%|██████▋   | 176/261 [01:10<00:39,  2.14it/s, scatter MntSweetProducts, MntGoldProds]

Summarize dataset:  67%|██████▋   | 176/261 [01:10<00:39,  2.14it/s, scatter MntGoldProds, MntGoldProds]

Summarize dataset:  68%|██████▊   | 177/261 [01:11<00:44,  1.89it/s, scatter MntGoldProds, MntGoldProds]

Summarize dataset:  68%|██████▊   | 177/261 [01:11<00:44,  1.89it/s, scatter NumDealsPurchases, MntGoldProds]

Summarize dataset:  68%|██████▊   | 178/261 [01:11<00:44,  1.85it/s, scatter NumDealsPurchases, MntGoldProds]

Summarize dataset:  68%|██████▊   | 178/261 [01:11<00:44,  1.85it/s, scatter NumWebPurchases, MntGoldProds]

Summarize dataset:  69%|██████▊   | 179/261 [01:12<00:41,  1.96it/s, scatter NumWebPurchases, MntGoldProds]

Summarize dataset:  69%|██████▊   | 179/261 [01:12<00:41,  1.96it/s, scatter NumCatalogPurchases, MntGoldProds]

Summarize dataset:  69%|██████▉   | 180/261 [01:12<00:38,  2.12it/s, scatter NumCatalogPurchases, MntGoldProds]

Summarize dataset:  69%|██████▉   | 180/261 [01:12<00:38,  2.12it/s, scatter NumStorePurchases, MntGoldProds]

Summarize dataset:  69%|██████▉   | 181/261 [01:13<00:36,  2.20it/s, scatter NumStorePurchases, MntGoldProds]

Summarize dataset:  69%|██████▉   | 181/261 [01:13<00:36,  2.20it/s, scatter NumWebVisitsMonth, MntGoldProds]

Summarize dataset:  70%|██████▉   | 182/261 [01:13<00:34,  2.28it/s, scatter NumWebVisitsMonth, MntGoldProds]

Summarize dataset:  70%|██████▉   | 182/261 [01:13<00:34,  2.28it/s, scatter ID, NumDealsPurchases]

Summarize dataset:  70%|███████   | 183/261 [01:13<00:32,  2.38it/s, scatter ID, NumDealsPurchases]

Summarize dataset:  70%|███████   | 183/261 [01:13<00:32,  2.38it/s, scatter Year_Birth, NumDealsPurchases]

Summarize dataset:  70%|███████   | 184/261 [01:14<00:31,  2.41it/s, scatter Year_Birth, NumDealsPurchases]

Summarize dataset:  70%|███████   | 184/261 [01:14<00:31,  2.41it/s, scatter Income, NumDealsPurchases]

Summarize dataset:  71%|███████   | 185/261 [01:14<00:31,  2.38it/s, scatter Income, NumDealsPurchases]

Summarize dataset:  71%|███████   | 185/261 [01:14<00:31,  2.38it/s, scatter Recency, NumDealsPurchases]

Summarize dataset:  71%|███████▏  | 186/261 [01:16<00:52,  1.43it/s, scatter Recency, NumDealsPurchases]

Summarize dataset:  71%|███████▏  | 186/261 [01:16<00:52,  1.43it/s, scatter MntWines, NumDealsPurchases]

Summarize dataset:  72%|███████▏  | 187/261 [01:16<00:46,  1.59it/s, scatter MntWines, NumDealsPurchases]

Summarize dataset:  72%|███████▏  | 187/261 [01:16<00:46,  1.59it/s, scatter MntFruits, NumDealsPurchases]

Summarize dataset:  72%|███████▏  | 188/261 [01:16<00:41,  1.77it/s, scatter MntFruits, NumDealsPurchases]

Summarize dataset:  72%|███████▏  | 188/261 [01:16<00:41,  1.77it/s, scatter MntMeatProducts, NumDealsPurchases]

Summarize dataset:  72%|███████▏  | 189/261 [01:17<00:38,  1.85it/s, scatter MntMeatProducts, NumDealsPurchases]

Summarize dataset:  72%|███████▏  | 189/261 [01:17<00:38,  1.85it/s, scatter MntFishProducts, NumDealsPurchases]

Summarize dataset:  73%|███████▎  | 190/261 [01:17<00:35,  1.99it/s, scatter MntFishProducts, NumDealsPurchases]

Summarize dataset:  73%|███████▎  | 190/261 [01:17<00:35,  1.99it/s, scatter MntSweetProducts, NumDealsPurchases]

Summarize dataset:  73%|███████▎  | 191/261 [01:18<00:33,  2.09it/s, scatter MntSweetProducts, NumDealsPurchases]

Summarize dataset:  73%|███████▎  | 191/261 [01:18<00:33,  2.09it/s, scatter MntGoldProds, NumDealsPurchases]

Summarize dataset:  74%|███████▎  | 192/261 [01:18<00:33,  2.04it/s, scatter MntGoldProds, NumDealsPurchases]

Summarize dataset:  74%|███████▎  | 192/261 [01:18<00:33,  2.04it/s, scatter NumDealsPurchases, NumDealsPurchases]

Summarize dataset:  74%|███████▍  | 193/261 [01:19<00:31,  2.18it/s, scatter NumDealsPurchases, NumDealsPurchases]

Summarize dataset:  74%|███████▍  | 193/261 [01:19<00:31,  2.18it/s, scatter NumWebPurchases, NumDealsPurchases]

Summarize dataset:  74%|███████▍  | 194/261 [01:19<00:29,  2.27it/s, scatter NumWebPurchases, NumDealsPurchases]

Summarize dataset:  74%|███████▍  | 194/261 [01:19<00:29,  2.27it/s, scatter NumCatalogPurchases, NumDealsPurchases]

Summarize dataset:  75%|███████▍  | 195/261 [01:19<00:29,  2.23it/s, scatter NumCatalogPurchases, NumDealsPurchases]

Summarize dataset:  75%|███████▍  | 195/261 [01:19<00:29,  2.23it/s, scatter NumStorePurchases, NumDealsPurchases]

Summarize dataset:  75%|███████▌  | 196/261 [01:20<00:29,  2.23it/s, scatter NumStorePurchases, NumDealsPurchases]

Summarize dataset:  75%|███████▌  | 196/261 [01:20<00:29,  2.23it/s, scatter NumWebVisitsMonth, NumDealsPurchases]

Summarize dataset:  75%|███████▌  | 197/261 [01:20<00:28,  2.21it/s, scatter NumWebVisitsMonth, NumDealsPurchases]

Summarize dataset:  75%|███████▌  | 197/261 [01:20<00:28,  2.21it/s, scatter ID, NumWebPurchases]

Summarize dataset:  76%|███████▌  | 198/261 [01:21<00:26,  2.39it/s, scatter ID, NumWebPurchases]

Summarize dataset:  76%|███████▌  | 198/261 [01:21<00:26,  2.39it/s, scatter Year_Birth, NumWebPurchases]

Summarize dataset:  76%|███████▌  | 199/261 [01:21<00:25,  2.41it/s, scatter Year_Birth, NumWebPurchases]

Summarize dataset:  76%|███████▌  | 199/261 [01:21<00:25,  2.41it/s, scatter Income, NumWebPurchases]

Summarize dataset:  77%|███████▋  | 200/261 [01:22<00:25,  2.40it/s, scatter Income, NumWebPurchases]

Summarize dataset:  77%|███████▋  | 200/261 [01:22<00:25,  2.40it/s, scatter Recency, NumWebPurchases]

Summarize dataset:  77%|███████▋  | 201/261 [01:22<00:25,  2.35it/s, scatter Recency, NumWebPurchases]

Summarize dataset:  77%|███████▋  | 201/261 [01:22<00:25,  2.35it/s, scatter MntWines, NumWebPurchases]

Summarize dataset:  77%|███████▋  | 202/261 [01:22<00:25,  2.33it/s, scatter MntWines, NumWebPurchases]

Summarize dataset:  77%|███████▋  | 202/261 [01:22<00:25,  2.33it/s, scatter MntFruits, NumWebPurchases]

Summarize dataset:  78%|███████▊  | 203/261 [01:23<00:27,  2.15it/s, scatter MntFruits, NumWebPurchases]

Summarize dataset:  78%|███████▊  | 203/261 [01:23<00:27,  2.15it/s, scatter MntMeatProducts, NumWebPurchases]

Summarize dataset:  78%|███████▊  | 204/261 [01:24<00:28,  2.00it/s, scatter MntMeatProducts, NumWebPurchases]

Summarize dataset:  78%|███████▊  | 204/261 [01:24<00:28,  2.00it/s, scatter MntFishProducts, NumWebPurchases]

Summarize dataset:  79%|███████▊  | 205/261 [01:24<00:27,  2.06it/s, scatter MntFishProducts, NumWebPurchases]

Summarize dataset:  79%|███████▊  | 205/261 [01:24<00:27,  2.06it/s, scatter MntSweetProducts, NumWebPurchases]

Summarize dataset:  79%|███████▉  | 206/261 [01:24<00:24,  2.21it/s, scatter MntSweetProducts, NumWebPurchases]

Summarize dataset:  79%|███████▉  | 206/261 [01:24<00:24,  2.21it/s, scatter MntGoldProds, NumWebPurchases]

Summarize dataset:  79%|███████▉  | 207/261 [01:25<00:23,  2.29it/s, scatter MntGoldProds, NumWebPurchases]

Summarize dataset:  79%|███████▉  | 207/261 [01:25<00:23,  2.29it/s, scatter NumDealsPurchases, NumWebPurchases]

Summarize dataset:  80%|███████▉  | 208/261 [01:25<00:22,  2.36it/s, scatter NumDealsPurchases, NumWebPurchases]

Summarize dataset:  80%|███████▉  | 208/261 [01:25<00:22,  2.36it/s, scatter NumWebPurchases, NumWebPurchases]

Summarize dataset:  80%|████████  | 209/261 [01:26<00:20,  2.50it/s, scatter NumWebPurchases, NumWebPurchases]

Summarize dataset:  80%|████████  | 209/261 [01:26<00:20,  2.50it/s, scatter NumCatalogPurchases, NumWebPurchases]

Summarize dataset:  80%|████████  | 210/261 [01:26<00:20,  2.48it/s, scatter NumCatalogPurchases, NumWebPurchases]

Summarize dataset:  80%|████████  | 210/261 [01:26<00:20,  2.48it/s, scatter NumStorePurchases, NumWebPurchases]

Summarize dataset:  81%|████████  | 211/261 [01:26<00:21,  2.38it/s, scatter NumStorePurchases, NumWebPurchases]

Summarize dataset:  81%|████████  | 211/261 [01:26<00:21,  2.38it/s, scatter NumWebVisitsMonth, NumWebPurchases]

Summarize dataset:  81%|████████  | 212/261 [01:27<00:20,  2.40it/s, scatter NumWebVisitsMonth, NumWebPurchases]

Summarize dataset:  81%|████████  | 212/261 [01:27<00:20,  2.40it/s, scatter ID, NumCatalogPurchases]

Summarize dataset:  82%|████████▏ | 213/261 [01:27<00:18,  2.54it/s, scatter ID, NumCatalogPurchases]

Summarize dataset:  82%|████████▏ | 213/261 [01:27<00:18,  2.54it/s, scatter Year_Birth, NumCatalogPurchases]

Summarize dataset:  82%|████████▏ | 214/261 [01:28<00:18,  2.59it/s, scatter Year_Birth, NumCatalogPurchases]

Summarize dataset:  82%|████████▏ | 214/261 [01:28<00:18,  2.59it/s, scatter Income, NumCatalogPurchases]

Summarize dataset:  82%|████████▏ | 215/261 [01:28<00:17,  2.64it/s, scatter Income, NumCatalogPurchases]

Summarize dataset:  82%|████████▏ | 215/261 [01:28<00:17,  2.64it/s, scatter Recency, NumCatalogPurchases]

Summarize dataset:  83%|████████▎ | 216/261 [01:28<00:17,  2.60it/s, scatter Recency, NumCatalogPurchases]

Summarize dataset:  83%|████████▎ | 216/261 [01:28<00:17,  2.60it/s, scatter MntWines, NumCatalogPurchases]

Summarize dataset:  83%|████████▎ | 217/261 [01:29<00:16,  2.68it/s, scatter MntWines, NumCatalogPurchases]

Summarize dataset:  83%|████████▎ | 217/261 [01:29<00:16,  2.68it/s, scatter MntFruits, NumCatalogPurchases]

Summarize dataset:  84%|████████▎ | 218/261 [01:29<00:16,  2.60it/s, scatter MntFruits, NumCatalogPurchases]

Summarize dataset:  84%|████████▎ | 218/261 [01:29<00:16,  2.60it/s, scatter MntMeatProducts, NumCatalogPurchases]

Summarize dataset:  84%|████████▍ | 219/261 [01:29<00:16,  2.53it/s, scatter MntMeatProducts, NumCatalogPurchases]

Summarize dataset:  84%|████████▍ | 219/261 [01:29<00:16,  2.53it/s, scatter MntFishProducts, NumCatalogPurchases]

Summarize dataset:  84%|████████▍ | 220/261 [01:30<00:16,  2.48it/s, scatter MntFishProducts, NumCatalogPurchases]

Summarize dataset:  84%|████████▍ | 220/261 [01:30<00:16,  2.48it/s, scatter MntSweetProducts, NumCatalogPurchases]

Summarize dataset:  85%|████████▍ | 221/261 [01:30<00:16,  2.38it/s, scatter MntSweetProducts, NumCatalogPurchases]

Summarize dataset:  85%|████████▍ | 221/261 [01:30<00:16,  2.38it/s, scatter MntGoldProds, NumCatalogPurchases]

Summarize dataset:  85%|████████▌ | 222/261 [01:31<00:15,  2.44it/s, scatter MntGoldProds, NumCatalogPurchases]

Summarize dataset:  85%|████████▌ | 222/261 [01:31<00:15,  2.44it/s, scatter NumDealsPurchases, NumCatalogPurchases]

Summarize dataset:  85%|████████▌ | 223/261 [01:31<00:15,  2.47it/s, scatter NumDealsPurchases, NumCatalogPurchases]

Summarize dataset:  85%|████████▌ | 223/261 [01:31<00:15,  2.47it/s, scatter NumWebPurchases, NumCatalogPurchases]

Summarize dataset:  86%|████████▌ | 224/261 [01:31<00:14,  2.59it/s, scatter NumWebPurchases, NumCatalogPurchases]

Summarize dataset:  86%|████████▌ | 224/261 [01:31<00:14,  2.59it/s, scatter NumCatalogPurchases, NumCatalogPurchases]

Summarize dataset:  86%|████████▌ | 225/261 [01:32<00:14,  2.41it/s, scatter NumCatalogPurchases, NumCatalogPurchases]

Summarize dataset:  86%|████████▌ | 225/261 [01:32<00:14,  2.41it/s, scatter NumStorePurchases, NumCatalogPurchases]

Summarize dataset:  87%|████████▋ | 226/261 [01:32<00:13,  2.52it/s, scatter NumStorePurchases, NumCatalogPurchases]

Summarize dataset:  87%|████████▋ | 226/261 [01:32<00:13,  2.52it/s, scatter NumWebVisitsMonth, NumCatalogPurchases]

Summarize dataset:  87%|████████▋ | 227/261 [01:33<00:13,  2.43it/s, scatter NumWebVisitsMonth, NumCatalogPurchases]

Summarize dataset:  87%|████████▋ | 227/261 [01:33<00:13,  2.43it/s, scatter ID, NumStorePurchases]

Summarize dataset:  87%|████████▋ | 228/261 [01:34<00:23,  1.41it/s, scatter ID, NumStorePurchases]

Summarize dataset:  87%|████████▋ | 228/261 [01:34<00:23,  1.41it/s, scatter Year_Birth, NumStorePurchases]

Summarize dataset:  88%|████████▊ | 229/261 [01:35<00:19,  1.65it/s, scatter Year_Birth, NumStorePurchases]

Summarize dataset:  88%|████████▊ | 229/261 [01:35<00:19,  1.65it/s, scatter Income, NumStorePurchases]

Summarize dataset:  88%|████████▊ | 230/261 [01:35<00:16,  1.84it/s, scatter Income, NumStorePurchases]

Summarize dataset:  88%|████████▊ | 230/261 [01:35<00:16,  1.84it/s, scatter Recency, NumStorePurchases]

Summarize dataset:  89%|████████▊ | 231/261 [01:35<00:14,  2.01it/s, scatter Recency, NumStorePurchases]

Summarize dataset:  89%|████████▊ | 231/261 [01:35<00:14,  2.01it/s, scatter MntWines, NumStorePurchases]

Summarize dataset:  89%|████████▉ | 232/261 [01:36<00:13,  2.13it/s, scatter MntWines, NumStorePurchases]

Summarize dataset:  89%|████████▉ | 232/261 [01:36<00:13,  2.13it/s, scatter MntFruits, NumStorePurchases]

Summarize dataset:  89%|████████▉ | 233/261 [01:36<00:14,  1.95it/s, scatter MntFruits, NumStorePurchases]

Summarize dataset:  89%|████████▉ | 233/261 [01:36<00:14,  1.95it/s, scatter MntMeatProducts, NumStorePurchases]

Summarize dataset:  90%|████████▉ | 234/261 [01:37<00:13,  1.96it/s, scatter MntMeatProducts, NumStorePurchases]

Summarize dataset:  90%|████████▉ | 234/261 [01:37<00:13,  1.96it/s, scatter MntFishProducts, NumStorePurchases]

Summarize dataset:  90%|█████████ | 235/261 [01:37<00:12,  2.04it/s, scatter MntFishProducts, NumStorePurchases]

Summarize dataset:  90%|█████████ | 235/261 [01:37<00:12,  2.04it/s, scatter MntSweetProducts, NumStorePurchases]

Summarize dataset:  90%|█████████ | 236/261 [01:38<00:11,  2.18it/s, scatter MntSweetProducts, NumStorePurchases]

Summarize dataset:  90%|█████████ | 236/261 [01:38<00:11,  2.18it/s, scatter MntGoldProds, NumStorePurchases]

Summarize dataset:  91%|█████████ | 237/261 [01:38<00:10,  2.21it/s, scatter MntGoldProds, NumStorePurchases]

Summarize dataset:  91%|█████████ | 237/261 [01:38<00:10,  2.21it/s, scatter NumDealsPurchases, NumStorePurchases]

Summarize dataset:  91%|█████████ | 238/261 [01:38<00:09,  2.32it/s, scatter NumDealsPurchases, NumStorePurchases]

Summarize dataset:  91%|█████████ | 238/261 [01:38<00:09,  2.32it/s, scatter NumWebPurchases, NumStorePurchases]

Summarize dataset:  92%|█████████▏| 239/261 [01:39<00:09,  2.41it/s, scatter NumWebPurchases, NumStorePurchases]

Summarize dataset:  92%|█████████▏| 239/261 [01:39<00:09,  2.41it/s, scatter NumCatalogPurchases, NumStorePurchases]

Summarize dataset:  92%|█████████▏| 240/261 [01:39<00:08,  2.39it/s, scatter NumCatalogPurchases, NumStorePurchases]

Summarize dataset:  92%|█████████▏| 240/261 [01:39<00:08,  2.39it/s, scatter NumStorePurchases, NumStorePurchases]

Summarize dataset:  92%|█████████▏| 241/261 [01:40<00:08,  2.37it/s, scatter NumStorePurchases, NumStorePurchases]

Summarize dataset:  92%|█████████▏| 241/261 [01:40<00:08,  2.37it/s, scatter NumWebVisitsMonth, NumStorePurchases]

Summarize dataset:  93%|█████████▎| 242/261 [01:40<00:08,  2.28it/s, scatter NumWebVisitsMonth, NumStorePurchases]

Summarize dataset:  93%|█████████▎| 242/261 [01:40<00:08,  2.28it/s, scatter ID, NumWebVisitsMonth]

Summarize dataset:  93%|█████████▎| 243/261 [01:41<00:08,  2.06it/s, scatter ID, NumWebVisitsMonth]

Summarize dataset:  93%|█████████▎| 243/261 [01:41<00:08,  2.06it/s, scatter Year_Birth, NumWebVisitsMonth]

Summarize dataset:  93%|█████████▎| 244/261 [01:41<00:07,  2.15it/s, scatter Year_Birth, NumWebVisitsMonth]

Summarize dataset:  93%|█████████▎| 244/261 [01:41<00:07,  2.15it/s, scatter Income, NumWebVisitsMonth]

Summarize dataset:  94%|█████████▍| 245/261 [01:42<00:07,  2.16it/s, scatter Income, NumWebVisitsMonth]

Summarize dataset:  94%|█████████▍| 245/261 [01:42<00:07,  2.16it/s, scatter Recency, NumWebVisitsMonth]

Summarize dataset:  94%|█████████▍| 246/261 [01:42<00:06,  2.20it/s, scatter Recency, NumWebVisitsMonth]

Summarize dataset:  94%|█████████▍| 246/261 [01:42<00:06,  2.20it/s, scatter MntWines, NumWebVisitsMonth]

Summarize dataset:  95%|█████████▍| 247/261 [01:43<00:06,  2.19it/s, scatter MntWines, NumWebVisitsMonth]

Summarize dataset:  95%|█████████▍| 247/261 [01:43<00:06,  2.19it/s, scatter MntFruits, NumWebVisitsMonth]

Summarize dataset:  95%|█████████▌| 248/261 [01:43<00:05,  2.24it/s, scatter MntFruits, NumWebVisitsMonth]

Summarize dataset:  95%|█████████▌| 248/261 [01:43<00:05,  2.24it/s, scatter MntMeatProducts, NumWebVisitsMonth]

Summarize dataset:  95%|█████████▌| 249/261 [01:43<00:05,  2.29it/s, scatter MntMeatProducts, NumWebVisitsMonth]

Summarize dataset:  95%|█████████▌| 249/261 [01:43<00:05,  2.29it/s, scatter MntFishProducts, NumWebVisitsMonth]

Summarize dataset:  96%|█████████▌| 250/261 [01:44<00:04,  2.29it/s, scatter MntFishProducts, NumWebVisitsMonth]

Summarize dataset:  96%|█████████▌| 250/261 [01:44<00:04,  2.29it/s, scatter MntSweetProducts, NumWebVisitsMonth]

Summarize dataset:  96%|█████████▌| 251/261 [01:44<00:04,  2.30it/s, scatter MntSweetProducts, NumWebVisitsMonth]

Summarize dataset:  96%|█████████▌| 251/261 [01:44<00:04,  2.30it/s, scatter MntGoldProds, NumWebVisitsMonth]

Summarize dataset:  97%|█████████▋| 252/261 [01:45<00:04,  2.16it/s, scatter MntGoldProds, NumWebVisitsMonth]

Summarize dataset:  97%|█████████▋| 252/261 [01:45<00:04,  2.16it/s, scatter NumDealsPurchases, NumWebVisitsMonth]

Summarize dataset:  97%|█████████▋| 253/261 [01:45<00:03,  2.15it/s, scatter NumDealsPurchases, NumWebVisitsMonth]

Summarize dataset:  97%|█████████▋| 253/261 [01:45<00:03,  2.15it/s, scatter NumWebPurchases, NumWebVisitsMonth]

Summarize dataset:  97%|█████████▋| 254/261 [01:46<00:03,  2.19it/s, scatter NumWebPurchases, NumWebVisitsMonth]

Summarize dataset:  97%|█████████▋| 254/261 [01:46<00:03,  2.19it/s, scatter NumCatalogPurchases, NumWebVisitsMonth]

Summarize dataset:  98%|█████████▊| 255/261 [01:46<00:02,  2.22it/s, scatter NumCatalogPurchases, NumWebVisitsMonth]

Summarize dataset:  98%|█████████▊| 255/261 [01:46<00:02,  2.22it/s, scatter NumStorePurchases, NumWebVisitsMonth]

Summarize dataset:  98%|█████████▊| 256/261 [01:47<00:02,  2.26it/s, scatter NumStorePurchases, NumWebVisitsMonth]

Summarize dataset:  98%|█████████▊| 256/261 [01:47<00:02,  2.26it/s, scatter NumWebVisitsMonth, NumWebVisitsMonth]

Summarize dataset:  98%|█████████▊| 257/261 [01:47<00:01,  2.26it/s, scatter NumWebVisitsMonth, NumWebVisitsMonth]

Summarize dataset:  98%|█████████▊| 257/263 [01:47<00:02,  2.26it/s, Missing diagram bar]

Summarize dataset:  98%|█████████▊| 258/263 [01:48<00:03,  1.59it/s, Missing diagram bar]

Summarize dataset:  98%|█████████▊| 258/263 [01:48<00:03,  1.59it/s, Missing diagram matrix]

Summarize dataset:  98%|█████████▊| 259/263 [01:50<00:03,  1.10it/s, Missing diagram matrix]

Summarize dataset:  98%|█████████▊| 259/263 [01:50<00:03,  1.10it/s, Take sample]

Summarize dataset:  99%|█████████▉| 260/263 [01:50<00:02,  1.10it/s, Detecting duplicates]

Summarize dataset:  99%|█████████▉| 261/263 [01:50<00:01,  1.10it/s, Get alerts]

Summarize dataset: 100%|█████████▉| 262/263 [01:50<00:00,  1.10it/s, Get reproduction details]

Summarize dataset: 100%|██████████| 263/263 [01:50<00:00,  1.10it/s, Completed]

Summarize dataset: 100%|██████████| 263/263 [01:50<00:00,  2.39it/s, Completed]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Generate report structure: 100%|██████████| 1/1 [00:26<00:00, 26.87s/it]

Generate report structure: 100%|██████████| 1/1 [00:26<00:00, 26.88s/it]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML: 100%|██████████| 1/1 [00:04<00:00,  4.42s/it]

Render HTML: 100%|██████████| 1/1 [00:04<00:00,  4.43s/it]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file: 100%|██████████| 1/1 [00:00<00:00, 15.74it/s]

#### Nhiệm vụ 2: dtale trên dữ liệu Marketing Campaign
> dtale mở một web-server và trình duyệt, nên ô này không chạy tự động trong notebook báo cáo (chạy trên máy: `pip install dtale`).

In [ ]:
import pandas as pd
import dtale
marketing_data = pd.read_csv("data/marketing_campaign.csv", sep='\t', encoding='utf-8-sig')
dtale.show(marketing_data).open_browser()

### 1.3.3. Bài tập thực hành 1 — SweetViz trên tập Marketing Campaign
**Tính năng chính của SweetViz:**
- Tạo báo cáo HTML tương tác chỉ với một dòng lệnh `sv.analyze(df)`; mỗi biến có thống kê (số lượng, thiếu, distinct, mean/median/std…) cùng biểu đồ phân bố.
- Hiển thị ma trận tương quan/liên hệ giữa các biến, kể cả biến phân loại (hệ số tương quan, uncertainty coefficient, correlation ratio).
- So sánh hai tập dữ liệu bằng `sv.compare([train, 'Train'], [test, 'Test'])` hoặc so sánh hai nhóm con bằng `sv.compare_intra(df, df['Education']=='PhD', ['PhD','Others'])`.
- Phân tích theo biến mục tiêu (`target_feat='Response'`) để xem mối quan hệ của từng biến với nhãn.
- Xuất báo cáo bằng `show_html(...)` (file HTML độc lập) hoặc `show_notebook()`.

**Cách sử dụng:** `pip install sweetviz` → `report = sv.analyze(df)` → `report.show_html('file.html')`.

In [12]:
import sweetviz as sv
marketing_data = pd.read_csv("data/marketing_campaign.csv", sep='\t', encoding='utf-8-sig')
report = sv.analyze(marketing_data)
report.show_html("Reports/sweetviz_report.html", open_browser=False)

                                             |          | [  0%]   00:00 -> (? left)

[Summarizing dataframe]                      |          | [  0%]   00:00 -> (? left)

Feature: ID                                  |▎         | [  3%]   00:00 -> (00:00 left)

Feature: ID                                  |▋         | [  7%]   00:03 -> (00:47 left)

Feature: Year_Birth                          |▋         | [  7%]   00:03 -> (00:47 left)

Feature: Year_Birth                          |█         | [ 10%]   00:05 -> (00:53 left)

Feature: Education                           |█         | [ 10%]   00:05 -> (00:53 left)

Feature: Education                           |█▎        | [ 13%]   00:06 -> (00:39 left)

Feature: Marital_Status                      |█▎        | [ 13%]   00:06 -> (00:39 left)

Feature: Marital_Status                      |█▋        | [ 17%]   00:07 -> (00:32 left)

Feature: Income                              |█▋        | [ 17%]   00:07 -> (00:32 left)

Feature: Income                              |██        | [ 20%]   00:11 -> (00:53 left)

Feature: Kidhome                             |██        | [ 20%]   00:11 -> (00:53 left)

Feature: Kidhome                             |██▎       | [ 23%]   00:12 -> (00:40 left)

Feature: Teenhome                            |██▎       | [ 23%]   00:12 -> (00:40 left)

Feature: Teenhome                            |██▋       | [ 27%]   00:13 -> (00:31 left)

Feature: Dt_Customer                         |██▋       | [ 27%]   00:13 -> (00:31 left)

Feature: Recency                             |███       | [ 30%]   00:13 -> (00:30 left)

Feature: Recency                             |███▎      | [ 33%]   00:15 -> (00:27 left)

Feature: MntWines                            |███▎      | [ 33%]   00:15 -> (00:27 left)

Feature: MntWines                            |███▋      | [ 37%]   00:18 -> (00:32 left)

Feature: MntFruits                           |███▋      | [ 37%]   00:18 -> (00:32 left)

Feature: MntFruits                           |████      | [ 40%]   00:21 -> (00:35 left)

Feature: MntMeatProducts                     |████      | [ 40%]   00:21 -> (00:35 left)

Feature: MntMeatProducts                     |████▎     | [ 43%]   00:24 -> (00:41 left)

Feature: MntFishProducts                     |████▎     | [ 43%]   00:24 -> (00:41 left)

Feature: MntFishProducts                     |████▋     | [ 47%]   00:27 -> (00:39 left)

Feature: MntSweetProducts                    |████▋     | [ 47%]   00:27 -> (00:39 left)

Feature: MntSweetProducts                    |█████     | [ 50%]   00:29 -> (00:37 left)

Feature: MntGoldProds                        |█████     | [ 50%]   00:29 -> (00:37 left)

Feature: MntGoldProds                        |█████▎    | [ 53%]   00:32 -> (00:35 left)

Feature: NumDealsPurchases                   |█████▎    | [ 53%]   00:32 -> (00:35 left)

Feature: NumDealsPurchases                   |█████▋    | [ 57%]   00:34 -> (00:32 left)

Feature: NumWebPurchases                     |█████▋    | [ 57%]   00:34 -> (00:32 left)

Feature: NumWebPurchases                     |██████    | [ 60%]   00:37 -> (00:30 left)

Feature: NumCatalogPurchases                 |██████    | [ 60%]   00:37 -> (00:30 left)

Feature: NumCatalogPurchases                 |██████▎   | [ 63%]   00:40 -> (00:30 left)

Feature: NumStorePurchases                   |██████▎   | [ 63%]   00:40 -> (00:30 left)

Feature: NumStorePurchases                   |██████▋   | [ 67%]   00:43 -> (00:26 left)

Feature: NumWebVisitsMonth                   |██████▋   | [ 67%]   00:43 -> (00:26 left)

Feature: NumWebVisitsMonth                   |███████   | [ 70%]   00:45 -> (00:24 left)

Feature: AcceptedCmp3                        |███████   | [ 70%]   00:45 -> (00:24 left)

Feature: AcceptedCmp3                        |███████▎  | [ 73%]   00:46 -> (00:16 left)

Feature: AcceptedCmp4                        |███████▎  | [ 73%]   00:46 -> (00:16 left)

Feature: AcceptedCmp4                        |███████▋  | [ 77%]   00:47 -> (00:11 left)

Feature: AcceptedCmp5                        |███████▋  | [ 77%]   00:47 -> (00:11 left)

Feature: AcceptedCmp5                        |████████  | [ 80%]   00:47 -> (00:07 left)

Feature: AcceptedCmp1                        |████████  | [ 80%]   00:47 -> (00:07 left)

Feature: AcceptedCmp1                        |████████▎ | [ 83%]   00:48 -> (00:05 left)

Feature: AcceptedCmp2                        |████████▎ | [ 83%]   00:48 -> (00:05 left)

Feature: AcceptedCmp2                        |████████▋ | [ 87%]   00:49 -> (00:03 left)

Feature: Complain                            |████████▋ | [ 87%]   00:49 -> (00:03 left)

Feature: Complain                            |█████████ | [ 90%]   00:49 -> (00:02 left)

Feature: Z_CostContact                       |█████████ | [ 90%]   00:49 -> (00:02 left)

Feature: Z_CostContact                       |█████████▎| [ 93%]   00:50 -> (00:01 left)

Feature: Z_Revenue                           |█████████▎| [ 93%]   00:50 -> (00:01 left)

Feature: Z_Revenue                           |█████████▋| [ 97%]   00:50 -> (00:00 left)

Feature: Response                            |█████████▋| [ 97%]   00:50 -> (00:00 left)

Feature: Response                            |██████████| [100%]   00:51 -> (00:00 left)

Feature: Response                            |          | [  0%]   00:00 -> (? left)

[Step 2/3] Processing Pairwise Features      |          | [  0%]   00:00 -> (? left)

[Step 2/3] Processing Pairwise Features      |█         | [ 10%]   00:00 -> (00:01 left)

[Step 2/3] Processing Pairwise Features      |█▋        | [ 17%]   00:00 -> (00:01 left)

[Step 2/3] Processing Pairwise Features      |██▍       | [ 24%]   00:00 -> (00:01 left)

[Step 2/3] Processing Pairwise Features      |█████▌    | [ 55%]   00:00 -> (00:00 left)

[Step 2/3] Processing Pairwise Features      |███████▏  | [ 72%]   00:00 -> (00:00 left)

[Step 2/3] Processing Pairwise Features      |████████▌ | [ 86%]   00:01 -> (00:00 left)

[Step 2/3] Processing Pairwise Features      |█████████▋| [ 97%]   00:01 -> (00:00 left)

[Step 2/3] Processing Pairwise Features      |          | [  0%]   00:00 -> (? left)

[Step 3/3] Generating associations graph     |          | [  0%]   00:00 -> (? left)

Done! Use 'show' commands to display/save.   |          | [  0%]   00:08 -> (? left)

Done! Use 'show' commands to display/save.   |██████████| [100%]   00:08 -> (00:00 left)

Report Reports/sweetviz_report.html was generated.

### 1.3.4. Bài tập thực hành 2 — AutoViz trên tập Marketing Campaign
**Tính năng chính của AutoViz:**
- Tự động vẽ nhiều loại biểu đồ (histogram, boxplot, scatter, pairplot, heatmap tương quan, violin, biểu đồ cột cho biến phân loại…) chỉ với một lệnh `AV.AutoViz(file)`; công cụ tự chọn biểu đồ phù hợp theo kiểu dữ liệu.
- Tự phát hiện và xử lý một số vấn đề dữ liệu như cột có tỉ lệ thiếu cao, cột hằng số, cột trùng, ngoại lai; có thể chỉ định biến mục tiêu `depVar`.
- Với tập lớn có thể lấy mẫu (`max_rows_analyzed`, `max_cols_analyzed`) để chạy nhanh; có thể xuất biểu đồ ra thư mục (`chart_format='png'`/`'html'`).

**Cách sử dụng:** `pip install autoviz` → `from autoviz.AutoViz_Class import AutoViz_Class` → `AV = AutoViz_Class(); AV.AutoViz('file.csv', sep='\t')`.
> AutoViz mở nhiều biểu đồ trong trình duyệt/notebook và thường xung đột phiên bản thư viện, nên ô code dưới đây chạy trên máy cá nhân.

In [ ]:
from autoviz.AutoViz_Class import AutoViz_Class
AV = AutoViz_Class()
dft = AV.AutoViz("data/marketing_campaign.csv", sep='\t')